"""empty message

Revision ID: b66867431d49
Revises: 667e2e9eba53
Create Date: 2022-01-17 15:46:25.311768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66867431d49'
down_revision = '667e2e9eba53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))

    default_website = 'https://example.com'
    op.execute(f"UPDATE venue SET website_link='{default_website}' WHERE website_link IS NULL;")

    op.alter_column('venue', 'website_link', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
